
version: '3'
tasks:
  clean:
    desc: Remove build artifacts and temporary files
    cmds:
      - rm -rf dist/

  test:
    desc: Run Go tests with coverage
    cmds:
      - go test -v ./... -coverprofile=coverage.out

  test-coverage:
    desc: Run tests and check coverage using go-test-coverage
    deps: [test]
    cmds:
      - go install github.com/vladopajic/go-test-coverage/v2@v2.18.4
      - go-test-coverage --config .testcoverage.yml

  lint:
    desc: Run golangci-lint (v1.64.5)
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5 run ./...

  build:
    desc: Build the versifyr executable for local platform
    cmds:
      - mkdir -p dist
      - go build -v -o dist/versifyr ./cmd/versifyr

  advance-version:
    desc: Advance project version using versifyr CLI. Usage task advance-version [VERSION=v1.2.3]
    vars:
      LATEST_TAG:
        sh: git describe --tags --abbrev=0 || echo "v0.0.0"
      CALCULATED_VERSION:
        sh: echo "{{.LATEST_TAG}}" | awk -F. '{$NF+=1; for(i=1;i<NF;i++) printf $i "."; print $NF}'
      NEXT_VERSION: '{{.VERSION | default .CALCULATED_VERSION}}'
    cmds:
      - ./dist/versifyr set version="{{.NEXT_VERSION}}"

