# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go2

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Test
        run: go test -v github.com/zukrin/versifyr/cmd/versifyr

      - name: Build-linux-amd64
        run: go build -v -o dist/linux-amd64/versifyr github.com/zukrin/versifyr/cmd/versifyr
      - name : Archive-linux-amd64
        run: tar -czvf dist/versifyr-linux-amd64.tar.gz dist/linux-amd64/versifyr

      - name: Build-darwin-amd64
        run: GOOS=darwin GOARCH=arm64 go build -v -o dist/darwin-arm64/versifyr github.com/zukrin/versifyr/cmd/versifyr
      - name: Archive-darwin-amd64
        run: tar -czvf dist/versifyr-darwin-arm64.tar.gz dist/darwin-arm64/versifyr

      - name: Build-darwin-arm64
        run: GOOS=darwin GOARCH=amd64 go build -v -o dist/darwin-amd64/versifyr github.com/zukrin/versifyr/cmd/versifyr
      - name: Archive-darwin-amd64
        run: tar -czvf dist/versifyr-darwin-amd64.tar.gz dist/darwin-amd64/versifyr

      - name: list files
        run: ls -laR dist

      - name: version
        run: echo "version=$(./dist/darwin-arm64/versifyr --version)" >> $GITHUB_OUTPUT
        id: version


      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: true

      # - name: Commit CHANGELOG.md
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     branch: main
      #     commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
      #     file_pattern: CHANGELOG.md
  
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/versifyr-linux-amd64.tar.gz
          asset_name: versifyr-linux-amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/versifyr-darwin-amd64.tar.gz
          asset_name: versifyr-darwin-amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin arm artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/versifyr-darwin-arm64.tar.gz
          asset_name: versifyr-darwin-arm64.tar.gz
          asset_content_type: application/gzip
    
